### ISSUE TITLE
Accounting Test Fails

### ISSUE THREAD

**Issue by jgkim** [chb/indivo_server#2]
If auth_system 'mychildrens' does not exist in the file 'utils/indivo_data.xml', then the accounting test from the integration test fails as there is no auth system called 'mychildrens'.

**Comment by thisisdhaas** [comment]
Nice catch--the test suite definitely shouldn't depend on indivo_data.xml. If you're interested in taking this on, it should be a pretty simple fix (check out [the code](https://github.com/chb/indivo_server/blob/v1.0.0/indivo/tests/integration/__init__.py#L21), which is where that auth system should be created for the tests). Otherwise, we'll take care of it when we get a chance.
